### ISSUE TITLE
Pass local options to phantom-pdf

### ISSUE THREAD

**Issue by smehrbrodt** [jsreport/toner-phantom#1]
I want to use toner-phantom to create a PDF with a header and footer. I see that this is supported in [phantom-html-to-pdf](https://github.com/pofider/phantom-html-to-pdf#local-options).

Is there a way to pass these options via toner-phantom?

**Comment by pofider** [comment]
I have just updated docs with better example. Is it understandable now?

**Comment by smehrbrodt** [comment]
Yes, thank you!

However, once I add these options, I get the following error:

```
~/memberhive/node_modules/toner-phantom/lib/phantom.js:12
    _req.options.isChildRequest = true;
                                ^
TypeError: Cannot set property 'isChildRequest' of undefined
    at processPart (~/memberhive/node_modules/toner-phantom/lib/phantom.js:12:33)
    at processHeaderAndFooter (~/memberhive/node_modules/toner-phantom/lib/phantom.js:24:5)
    at Object.recipe [as phantom-pdf] (~/memberhive/node_modules/toner-phantom/lib/phantom.js:36:5)
    at ~/memberhive/node_modules/toner/lib/toner.js:126:47
    at ~/memberhive/node_modules/toner/lib/toner.js:85:17
    at collection.fire (~/memberhive/node_modules/toner/lib/listeners.js:18:16)
    at ~/memberhive/node_modules/toner/lib/toner.js:80:31
    at Request._callback (~/memberhive/node_modules/toner/node_modules/script-manager/lib/manager-servers.js:197:9)
    at Request.self.callback (~/memberhive/node_modules/toner/node_modules/script-manager/node_modules/request/request.js:344:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (~/memberhive/node_modules/toner/node_modules/script-manager/node_modules/request/request.js:1239:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (~/memberhive/node_modules/toner/node_modules/script-manager/node_modules/request/request.js:1187:12)
    at emitNone (events.js:72:20)
```

This is part of my code:

``` javascript
toner.render({
  template: {
    engine: 'none',
    recipe: 'phantom-pdf',
    content: result,
    phantom: {
      header: "some header"
    }
  }
});
```

**Comment by pofider** [comment]
Ups, bug!

Simple workaround, add empty options:

``` js
toner.render({
  template: {
    engine: 'none',
    recipe: 'phantom-pdf',
    content: result,
    phantom: {
      header: "some header"
    }
  },
 options: {}
});
```

**Comment by smehrbrodt** [comment]
Thanks, that works!
Should I leave this issue open until that bug is fixed?

**Comment by pofider** [comment]
Yes please, I will close it when it is deployed to NPM so other people see the workaround until then.

**Comment by pofider** [comment]
There are new NPM packages. This should run now without a workaround.
